variables:
    GIT_SUBMODULE_STRATEGY: recursive
    PHOENIX_PATH_PRODUCTION_PLUGINS: /htdocs/wp-content/plugins
    PHOENIX_PATH_TEST_PLUGINS: /var/www/phoenix/wp-content/plugins
    PROJECT_NAME: rh-fury
    WDEX_PATH_PRODUCTION_PLUGINS: /htdocs/wp-content/plugins
    WD50_PATH_PRODUCTION_PLUGINS: /htdocs/wp-content/plugins
    WD50_PATH_PRODUCTION_THEMES: /htdocs/wp-content/themes
    WD50_PATH_TEST_PLUGINS: /var/www/wd50/wp-content/plugins
    WD50_PATH_TEST_THEMES: /var/www/wd50/wp-content/themes

before_script:
    - git clone --branch=master --depth=1 --quiet git@git.aurora.ci:meta/deploy-script.git
    - chmod +x deploy-script/*.sh

stages:
    - code sniffer
    - test
    - production

webdesign.extern:
    stage: production
    
    script:
        - cd deploy-script
        - ./deploy.sh -u $DEPLOY_SERVER -d $DEPLOY_PATH -h $DEPLOY_SERVER
    
    only:
        - tags
    
    variables:
        DEPLOY_PATH: ${WDEX_PATH_PRODUCTION_PLUGINS}/${PROJECT_NAME}
        DEPLOY_SERVER: webdesign.extern.regiohelden.de

wd50.extern:
    stage: production
    
    script:
        - cd deploy-script
        - ./deploy.sh -u $DEPLOY_SERVER -d $DEPLOY_PATH -h $DEPLOY_SERVER
    
    only:
        - tags
    
    variables:
        DEPLOY_PATH: ${WD50_PATH_PRODUCTION_PLUGINS}/${PROJECT_NAME}
        DEPLOY_SERVER: wd50.extern.regiohelden.de

rh.de:
    stage: production
    
    script:
        - cd deploy-script
        - ./deploy.sh -u $DEPLOY_SERVER -d $DEPLOY_PATH -h $DEPLOY_SERVER
    
    only:
        - tags
    
    variables:
        DEPLOY_PATH: ${PHOENIX_PATH_PRODUCTION_PLUGINS}/${PROJECT_NAME}
        DEPLOY_SERVER: regiohelden.de

upload_phoenix_northstar:
    stage: test

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_TEST -d $DEPLOY_PATH -h $DEPLOY_SERVER

    only:
        - master

    variables:
        DEPLOY_PATH: ${PHOENIX_PATH_TEST_PLUGINS}/${PROJECT_NAME}
        DEPLOY_SERVER: northstar.li

        # GitLab group variables:
        # - SSH_USER_TEST

upload_wd50_northstar:
    stage: test

    script:
        - cd deploy-script
        - ./deploy.sh -u $SSH_USER_TEST -d $DEPLOY_PATH -h $DEPLOY_SERVER --zip

    only:
        - master

    variables:
        DEPLOY_PATH: ${WD50_PATH_TEST_PLUGINS}/${PROJECT_NAME}
        DEPLOY_SERVER: northstar.li

        # GitLab group variables:
        # - SSH_USER_TEST

code_sniffer:
    stage: code sniffer
    
    script:
        - cp /home/gitlab-runner/phpcs/ruleset.xml .
        - sed -i "s/PROJECT_NAME/${PROJECT_NAME/-/_}/g" ruleset.xml
        - phpcs --standard=ruleset.xml *
    
    only:
        - master
    
    allow_failure: true